name: Fetch Gold Price

on:
  schedule:
    - cron: "*/30 * * * *"   # run every 30 minutes
  workflow_dispatch:          # allow manual runs

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium

      - name: Run fetch script
        run: python fetch_gold.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gold.json
          git commit -m "Update gold price [skip ci]" || echo "No changes to commit"
          git push
